---
clickhouse:
  hosts:
    centos9-1:
      ansible_host: 158.160.38.209
      ansible_connection: ssh
      ansible_user: cloud-user
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      ansible_python_interpreter: /usr/bin/python3

vector:
  hosts:
    centos9-2:
      ansible_host: 158.160.114.214
      ansible_connection: ssh
      ansible_user: cloud-user
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      ansible_python_interpreter: /usr/bin/python3

lighthouse:
  hosts:
    centos9-3:
      ansible_host: 158.160.103.194
      ansible_connection: ssh
      ansible_user: cloud-user
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      ansible_python_interpreter: /usr/bin/python3
